{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pulsar-monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pulsar-monitor.labels" . | indent 4 }}
{{- end -}}
