{
 "title": "Billing Usage Estimator",
 "time": { "from": "now-10d", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "query": { "query": "label_values(namespace)" } },
   { "name": "topic_hour_price", "query": "0.0012" },
   { "name": "storage_month_price", "query": "0.07" },
   { "name": "write_price", "query": "0.12" },
   { "name": "read_price", "query": "0.05" },
   { "name": "function_bandwidth_price", "query": "0.04" },
   { "name": "function_instance_price", "query": "0.017" }
  ]
 },
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topic/Partition Hours - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(pulsar_topics_count{namespace=~\"$tenant.*\"})[$__range:1m])/60"
    }
   ]
  },
  {
   "title": "Topic/Partition Hours Cost - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(pulsar_topics_count{namespace=~\"$tenant.*\"})[$__range:1m])/60*$topic_hour_price"
    }
   ]
  },
  {
   "title": "Storage GB Months - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sum(avg_over_time(pulsar_storage_size{namespace=~\"$tenant.*\"}[1m]))[$__range:1m]))/2/43200/1024/1024/1024\n"
    }
   ]
  },
  {
   "title": "Storage GB Months Cost - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sum(avg_over_time(pulsar_storage_size{namespace=~\"$tenant.*\"}[1m]))[$__range:1m]))/2/43200/1024/1024/1024*$storage_month_price"
    }
   ]
  },
  {
   "title": "Write GB (pulsar_in) - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(increase(sum(pulsar_in_bytes_total{namespace=~\"$tenant.*\"})[$__range:1m]) > (increase(sum(pulsar_in_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512) or (increase(sum(pulsar_in_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512)))/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Write GB Cost - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(increase(sum(pulsar_in_bytes_total{namespace=~\"$tenant.*\"})[$__range:1m]) > (increase(sum(pulsar_in_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512) or (increase(sum(pulsar_in_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512)))/1024/1024/1024*$write_price"
    }
   ]
  },
  {
   "title": "Read GB (pulsar_out) - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(increase((pulsar_out_bytes_total{namespace=~\"$tenant.*\"})[$__range:1m]) > (increase(sum(pulsar_out_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512) or (increase(sum(pulsar_out_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512)))/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Read GB Cost - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(increase((pulsar_out_bytes_total{namespace=~\"$tenant.*\"})[$__range:1m]) > (increase(sum(pulsar_out_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512) or (increase(sum(pulsar_out_messages_total{namespace=~\"$tenant.*\"})[$__range:1m])*512)))/1024/1024/1024*$read_price",
     "legendFormat": "{{namespace}}-price"
    }
   ]
  },
  {
   "title": "Function Read GB - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=~\".*$tenant.*\", pod=~\"pf-$tenant.*\"}[$__range])) /1024/1024/1024"
    }
   ]
  },
  {
   "title": "Function Read GB Cost - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=~\".*$tenant.*\", pod=~\"pf-$tenant.*\"}[$__range])) /1024/1024/1024* $function_bandwidth_price"
    }
   ]
  },
  {
   "title": "Function Write GB - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(container_network_receive_bytes_total{pod=~\"pf-$tenant.*\"}[$__range])) /1024/1024/1024"
    }
   ]
  },
  {
   "title": "Function Write GB Cost - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(container_network_receive_bytes_total{pod=~\"pf-$tenant.*\"}[$__range])) /1024/1024/1024 * $function_bandwidth_price",
     "legendFormat": "{{pod}}-price"
    }
   ]
  },
  {
   "title": "Function Instance Hours - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sum(up{kubernetes_pod_name=~\"pf-$tenant.*\"})[$__range:1m])/60)"
    }
   ]
  },
  {
   "title": "Function Instance Hour Cost - $tenant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sum(up{kubernetes_pod_name=~\"pf-$tenant.*\"})[$__range:1m])/60)* $function_instance_price"
    }
   ]
  }
 ]
}