{
 "title": "Pulsar / Debezium Source",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connected Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_Connected{context=\"streaming\"}"
    }
   ]
  },
  {
   "title": "Events Seen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}"
    },
    {},
    {},
    {}
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_NumberOfCommittedTransactions{context=\"streaming\"}"
    }
   ]
  }
 ]
}