{{- if .Values.extra.zookeepernp }}
{{- if .Values.zookeepernp.pdb.usePolicy }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeepernp.component }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.zookeepernp.component }}
    cluster: {{ template "pulsar.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "pulsar.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.zookeepernp.component }}
  maxUnavailable: {{ .Values.zookeepernp.pdb.maxUnavailable }}
{{- end }}
{{- end }}
