{{- if .Values.extra.zookeepernp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "pulsar.fullname" . }}-zookeeper-config"
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "zookeeper-config"
    cluster: {{ template "pulsar.fullname" . }}
data:
  generate-zookeeper-config-mixed.sh: |
    #! /bin/bash
    CONF_FILE=$1

    if [ $? != 0 ]; then
        echo "Error: Failed to apply changes to config file"
        exit 1
    fi

    # Generate list of servers and detect the current server ID,
    # based on the hostname
    IDX=1
    for SERVER in $(echo $ZOOKEEPER_SERVERS | tr "," "\n")
    do
        echo "server.$IDX=$SERVER:2888:3888" >> $CONF_FILE

        if [[ "$SERVER" == ${HOSTNAME}* ]]; then
            MY_ID=$IDX
            echo "Current server id $MY_ID"
        fi

        ((IDX++))
    done

    # For ZooKeeper container we need to initialize the ZK id
    if [ ! -z "$MY_ID" ]; then
        # Get ZK data dir
        DATA_DIR=`grep '^dataDir=' $CONF_FILE | awk -F= '{print $2}'`
        if [ ! -e $DATA_DIR/myid ]; then
            echo "Creating $DATA_DIR/myid with id = $MY_ID"
            mkdir -p $DATA_DIR
            echo $MY_ID > $DATA_DIR/myid
        fi
    fi
{{- end }}