{{- if .Values.extra.zookeepernp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeepernp.component }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.zookeepernp.component }}
    cluster: {{ template "pulsar.fullname" . }}
data:
  {{- if and .Values.enableTls .Values.tls.zookeeper.enabled}}
  PULSAR_PREFIX_serverCnxnFactory: org.apache.zookeeper.server.NettyServerCnxnFactory
  serverCnxnFactory: org.apache.zookeeper.server.NettyServerCnxnFactory
  secureClientPort: "2281"
  PULSAR_PREFIX_secureClientPort: "2281"
  sslQuorum: "true"
  PULSAR_PREFIX_sslQuorum: "true"
  {{- end }}
{{ toYaml .Values.zookeepernp.configData | indent 2 }}
{{- end }}
