{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: pulsar-priority
value: {{ .Values.priorityClass.value }}
globalDefault: false
description: "This priority class is used for Pulsar pods."
{{- end }}
