{{- if .Values.extra.pulsarMonitor }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "pulsar.fullname" . }}-{{ .Values.pulsarMonitor.component }}-config"
data:
  runtime.yml: |-
    name: {{ .Values.pulsarMonitor.config.name }}
    token: {{ .Values.pulsarMonitor.config.pulsarClientToken }}
    tokenFilePath: {{ .Values.pulsarMonitor.config.tokenFilePath }} 
    trustStore: {{ .Values.pulsarMonitor.config.trustStore }}
    analyticsConfig:
      apiKey: {{ .Values.pulsarMonitor.config.analyticsApiKey }}
      ingestionURL: {{ .Values.pulsarMonitor.config.analyticsUrl }}
      insightsWriteKey: {{ .Values.pulsarMonitor.config.insightsWriteKey }}
      insightsAccountId: "{{ .Values.pulsarMonitor.config.insightsAccountId }}"
    prometheusConfig:
      port: ":{{ .Values.pulsarMonitor.port }}"
      exposeMetrics: {{ .Values.pulsarMonitor.prometheus.enabled }}
      prometheusProxyURL: {{ .Values.pulsarMonitor.prometheus.proxyURL }}
      prometheusProxyAPIKey: {{ .Values.pulsarMonitor.prometheus.proxyAPIKey }}
    slackConfig:
      alertUrl: {{ .Values.pulsarMonitor.config.alertUrl }}
    sitesConfig:
      sites:
        {{- toYaml .Values.pulsarMonitor.config.sitesConfig | nindent 8 }}
    opsGenieConfig:
      intervalSeconds: 180
      heartbeatKey: {{ .Values.pulsarMonitor.config.opsGenieHeartbeatKey }}
      heartbeatUrl: {{ .Values.pulsarMonitor.config.opsGenieHeartbeatUrl }}
      alertKey: {{ .Values.pulsarMonitor.config.opsGenieAlertKey }}
    k8sConfig:
      enabled: {{ .Values.pulsarMonitor.config.k8sInClusterMonitorEnabled }}
    brokersConfig:
      {{- toYaml .Values.pulsarMonitor.config.inclusterBrokerConfig | nindent 6 }}
    pulsarAdminRestConfig:
      intervalSeconds: 120
      token: {{ .Values.pulsarMonitor.config.pulsarClientToken }}
      clusters:
        {{- toYaml .Values.pulsarMonitor.config.pulsarOpsClusters | nindent 8 }}
    pulsarTopicConfig:
        {{- toYaml .Values.pulsarMonitor.config.topicConfigs | nindent 8 }}
    websocketConfig:
      {{- toYaml .Values.pulsarMonitor.config.pulsarWebSocketConfigs | nindent 8 }}
{{- end }}