{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "teleport.fullname" . }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "teleport.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "teleport.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.config.restricted_users.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted 
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: restricted
{{- end }}