{{- if .Values.rbac.create -}}
{{- if .Values.highPriority.enabled }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-priority-teleport
value: 1000000
globalDefault: false
description: "This priority class should be used for Teleport pods only."
{{- end }}
{{- end }}
