
persistence: no
enableAntiAffinity: no

zookeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "-Xms512m -Xmx512m -Dzookeeper.forceSync=yes"

bookkeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    BOOKIE_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"

broker:
  component: broker
  replicaCount: 1
  ledger:
    defaultEnsembleSize: 1
    defaultAckQuorum: 1
    defaultWriteQuorum: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"

autoRecovery:
  resources:
    requests:
      memory: 512Mi
      cpu: 1

function:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    BOOKIE_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"

proxy:
  replicaCount: 1 
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3 
  wsResources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"
  
