{{- if .Values.extra.kubectlProxy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "pulsar.fullname" . }}-kubectl-proxy"
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "{{ template "pulsar.fullname" . }}-kubectl-proxy"
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "pulsar.fullname" . }}-kubectl-proxy-viewer"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ template "pulsar.fullname" . }}-kubectl-proxy"
subjects:
- kind: ServiceAccount
  name: "{{ template "pulsar.fullname" . }}-kubectl-proxy"
  namespace: {{ .Release.Namespace }}
{{- end }}
