
persistence: no
enableTests: yes
extra:
  autoRecovery: no
  bastion: no
  pulsarMonitor: no

image:
  broker:
    repository: apachepulsar/pulsar

zookeeper:
  resources:
    requests:
      memory: 400Mi
      cpu: 0.3 
  configData:
    PULSAR_MEM: "\"-Xms256m -Xmx400m -Dcom.sun.management.jmxremote -Djute.maxbuffer=10485760 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC -XX:+PerfDisableSharedMem -Dzookeeper.forceSync=no\""

bookkeeper:
  replicaCount: 2
  resources:
    requests:
      memory: 400Mi
      cpu: 0.3 
  configData:
    BOOKIE_MEM: "\"-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -XX:G1LogLevel=finest\""
    BOOKIE_GC: "\"-XX:+UseG1GC -XX:MaxGCPauseMillis=10\""


broker:
  component: broker
  replicaCount: 1
  resources:
    requests:
      memory: 400Mi
      cpu: 0.3 
  configData:
    PULSAR_MEM: "\"-Xms256m -Xmx400m -XX:MaxDirectMemorySize=400m -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem\""

function:
  replicaCount: 1
  resources:
    requests:
      memory: 400Mi
      cpu: 0.3 
  configData:
    PULSAR_MEM: "\"-Xms256m -Xmx400m -XX:MaxDirectMemorySize=400m -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem\""

proxy:
  replicaCount: 1 
  resources:
    requests:
      memory: 400Mi
      cpu: 0.3 
  wsResources:
    requests:
      memory: 400Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "\"-Xms256m -Xmx400m -XX:MaxDirectMemorySize=400m\""
  
